### PR TITLE
Api docker fix

### LINKED ISSUE #291: API Docker container errors
**Describe the bug**
After medicines API docker container is built it

```sh
docker build . -t api
```

It fail to run when you try the following:

```sh
docker run -p 8080:8000 api
```

with the following error:
```
/api: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
```

**To Reproduce**

1. Open your terminal
2. Go to following folder ` medicines/api`
3. Build docker container  `docker build . -t api`
4. Run docker container `docker run -p 8080:8000 api`

**Expected behavior**
When I run docker container I should see a server logs showing is running

### PR DESCRIPTION
**Pull request by rjkerrison**
### Name of the story

Fixes #291 

Ship it

### Acceptance Criteria

- [ ] The docker container successfully runs of the GraphQL API

### Testing information

In `/medicines/api`, run `docker-compose build && docker-compose up`.
Go to http://localhost:8000/graphiql and make a few GraphQL requests.

### Pre-flight Checklist

- [ ] Tests
- [ ] DUXD review approval
- [ ] Accessibility Reviewed
- [ ] Product owner demo

### Pre-merge Checklist

- [ ] Branch test approved

### CODE REVIEW

File: medicines/api/src/azure_search.rs [hunk 1]
```diff
@@ -56,7 +56,15 @@ impl juniper::Context for AzureContext {}
 
 fn get_env(key: &str) -> String {
     match std::env::var(key) {
-        Ok(b) => b,
+        Ok(b) => {
```
Comment (TimboTambo) [inline medicines/api/src/azure_search.rs]: What is `b` here? Is there a more descriptive name that coud be used here that would make this more obvious?

Comment (pataruco) [reply medicines/api/src/azure_search.rs]: +1

Comment (rjkerrison) [reply medicines/api/src/azure_search.rs]: could maybe change it to `v` but was aiming for short names for tiny scope
